replicaCount: 1
image:
  repository: $repository
  tag: "$tag"
  pullPolicy: Always
extraLabels:
  "ID": "$service_id"
gitlab:
  app: "$app_name"
  envURL: "$repo_url"
service:
  enabled: true
  name: "web"
  url: "$public_url"
  additionalHosts:
    - ${app_name_in_url}-${ref_name}.${kube_ingress_base_domain}
  type: ClusterIP
  externalPort: 8080
  internalPort: 80
ingress:
  enabled: true
  path: "/"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
extraVolumes:
  - name: basic-auth
    secret:
      defaultMode: 444
      secretName: basic-auth
extraVolumeMounts:
  - mountPath: /etc/nginx/auth
    name: basic-auth
    readOnly: true
    subPath: auth